/**
 * Sync ABI + bytecode exports from packages/contracts/out/ into
 * src/contracts/abis/ + src/contracts/bytecode/.
 * Run after `forge build` in @regista11/contracts whenever the contract
 * surface changes.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const CONTRACTS_OUT = resolve(HERE, "../../contracts/out");
const ABIS_DIR = resolve(HERE, "../src/contracts/abis");
const BYTECODE_DIR = resolve(HERE, "../src/contracts/bytecode");

interface Target {
  artifactPath: string;
  abiExportName: string;
  bytecodeExportName: string | null; // null = interface, no bytecode
  outFile: string;
}

const TARGETS: Target[] = [
  {
    artifactPath: "PropMarketHookFactory.sol/PropMarketHookFactory.json",
    abiExportName: "PropMarketHookFactoryABI",
    bytecodeExportName: "PropMarketHookFactoryBytecode",
    outFile: "PropMarketHookFactory.ts",
  },
  {
    artifactPath: "PropMarketHook.sol/PropMarketHook.json",
    abiExportName: "PropMarketHookABI",
    bytecodeExportName: "PropMarketHookBytecode",
    outFile: "PropMarketHook.ts",
  },
  {
    artifactPath: "IUSDT0.sol/IUSDT0.json",
    abiExportName: "IUSDT0ABI",
    bytecodeExportName: null,
    outFile: "IUSDT0.ts",
  },
];

function readArtifact(t: Target) {
  const full = resolve(CONTRACTS_OUT, t.artifactPath);
  if (!existsSync(full)) {
    throw new Error(
      `forge artifact missing: ${full}\nRun \`pnpm --filter @regista11/contracts build\` first.`
    );
  }
  return JSON.parse(readFileSync(full, "utf8"));
}

function syncAbi(t: Target): void {
  const artifact = readArtifact(t);
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`artifact at ${t.artifactPath} has no .abi array`);
  }
  const body =
    `// AUTO-GENERATED by script/sync-abis.ts. DO NOT EDIT BY HAND.\n` +
    `// Source: packages/contracts/out/${t.artifactPath}\n` +
    `export const ${t.abiExportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  const outPath = resolve(ABIS_DIR, t.outFile);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, body);
  process.stdout.write(`wrote ${outPath}\n`);
}

function syncBytecode(t: Target): void {
  if (!t.bytecodeExportName) return;
  const artifact = readArtifact(t);
  const obj = artifact?.bytecode?.object;
  if (typeof obj !== "string" || !obj.startsWith("0x")) {
    throw new Error(`artifact ${t.artifactPath} missing bytecode.object (got: ${typeof obj})`);
  }
  const body =
    `// AUTO-GENERATED by script/sync-abis.ts. DO NOT EDIT BY HAND.\n` +
    `// Source: packages/contracts/out/${t.artifactPath} (.bytecode.object)\n` +
    `export const ${t.bytecodeExportName} = "${obj}" as const;\n`;
  const outPath = resolve(BYTECODE_DIR, t.outFile);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, body);
  process.stdout.write(`wrote ${outPath}\n`);
}

function writeAbiBarrel(): void {
  const body =
    `// AUTO-GENERATED barrel from script/sync-abis.ts. DO NOT EDIT BY HAND.\n` +
    TARGETS.map(
      (t) =>
        `export { ${t.abiExportName} } from "./${t.outFile.replace(/\.ts$/, ".js")}";`
    ).join("\n") +
    "\n";
  writeFileSync(resolve(ABIS_DIR, "index.ts"), body);
  process.stdout.write(`wrote ${resolve(ABIS_DIR, "index.ts")}\n`);
}

function writeBytecodeBarrel(): void {
  const entries = TARGETS.filter((t) => t.bytecodeExportName);
  const body =
    `// AUTO-GENERATED barrel from script/sync-abis.ts. DO NOT EDIT BY HAND.\n` +
    entries
      .map(
        (t) =>
          `export { ${t.bytecodeExportName} } from "./${t.outFile.replace(/\.ts$/, ".js")}";`
      )
      .join("\n") +
    "\n";
  mkdirSync(BYTECODE_DIR, { recursive: true });
  writeFileSync(resolve(BYTECODE_DIR, "index.ts"), body);
  process.stdout.write(`wrote ${resolve(BYTECODE_DIR, "index.ts")}\n`);
}

for (const t of TARGETS) {
  syncAbi(t);
  syncBytecode(t);
}
writeAbiBarrel();
writeBytecodeBarrel();
