#!/usr/bin/env node
/**
 * Sync ABIs from packages/contracts/out/ into packages/web/src/abis/ as
 * `as const` TypeScript exports for viem's typed-contract inference.
 *
 * Mirrors packages/agent/script/sync-abis.ts, but emits only ABIs (no
 * bytecode — the web app never deploys) and lands them in web's tree.
 *
 * Also copies the on-disk deployment artifact into web's bundled data when
 * one exists. The web app reads `src/data/deployments.json` directly via
 * Next.js's JSON import support.
 *
 * Idempotent. Safe to re-run on every `forge build`.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const CONTRACTS_OUT = resolve(HERE, "../../contracts/out");
const ABIS_DIR = resolve(HERE, "../src/abis");
const DATA_DIR = resolve(HERE, "../src/data");
const DEPLOYMENT_SRC = resolve(HERE, "../../contracts/deployments/xlayer-mainnet.json");
const DEPLOYMENT_DST = resolve(DATA_DIR, "deployments.json");

const TARGETS = [
  {
    artifactPath: "PropMarketHookFactory.sol/PropMarketHookFactory.json",
    abiExportName: "PropMarketHookFactoryABI",
    outFile: "PropMarketHookFactory.ts",
  },
  {
    artifactPath: "PropMarketHook.sol/PropMarketHook.json",
    abiExportName: "PropMarketHookABI",
    outFile: "PropMarketHook.ts",
  },
  {
    artifactPath: "IUSDT0.sol/IUSDT0.json",
    abiExportName: "IUSDT0ABI",
    outFile: "IUSDT0.ts",
  },
];

function syncAbi(t) {
  const full = resolve(CONTRACTS_OUT, t.artifactPath);
  if (!existsSync(full)) {
    process.stderr.write(
      `[sync-abis] WARNING: artifact missing: ${full}\n` +
        `              Run \`pnpm --filter @regista11/contracts build\` first.\n`,
    );
    return;
  }
  const artifact = JSON.parse(readFileSync(full, "utf8"));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`artifact at ${t.artifactPath} has no .abi array`);
  }
  const body =
    `// AUTO-GENERATED by packages/web/scripts/sync-abis.mjs. DO NOT EDIT BY HAND.\n` +
    `// Source: packages/contracts/out/${t.artifactPath}\n` +
    `export const ${t.abiExportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  const outPath = resolve(ABIS_DIR, t.outFile);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, body);
  process.stdout.write(`[sync-abis] wrote ${outPath}\n`);
}

function writeAbiBarrel() {
  const lines = TARGETS.map(
    (t) => `export { ${t.abiExportName} } from "./${t.outFile.replace(/\.ts$/, "")}";`,
  );
  const body =
    `// AUTO-GENERATED barrel by packages/web/scripts/sync-abis.mjs. DO NOT EDIT BY HAND.\n` +
    lines.join("\n") +
    "\n";
  writeFileSync(resolve(ABIS_DIR, "index.ts"), body);
  process.stdout.write(`[sync-abis] wrote ${resolve(ABIS_DIR, "index.ts")}\n`);
}

function syncDeployment() {
  mkdirSync(DATA_DIR, { recursive: true });
  if (existsSync(DEPLOYMENT_SRC)) {
    copyFileSync(DEPLOYMENT_SRC, DEPLOYMENT_DST);
    process.stdout.write(`[sync-abis] copied deployment artifact → ${DEPLOYMENT_DST}\n`);
    return;
  }
  if (existsSync(DEPLOYMENT_DST)) {
    process.stdout.write(
      `[sync-abis] no contracts deployment found; keeping existing ${DEPLOYMENT_DST}\n`,
    );
    return;
  }
  const stub = {
    chainId: 196,
    network: "xlayer-mainnet",
    deployed: false,
    deployedAt: null,
    deployedAtBlock: null,
    deployer: null,
    resolver: null,
    contracts: { PropMarketHookFactory: null },
    knownExternal: {
      poolManager: "0x360E68faCcca8cA495c1B759Fd9EEe466db9FB32",
      usdt0: "0x779Ded0c9e1022225f8E0630b35a9b54bE713736",
    },
    agents: null,
    version: "0.0.0-undeployed",
  };
  writeFileSync(DEPLOYMENT_DST, JSON.stringify(stub, null, 2) + "\n");
  process.stdout.write(`[sync-abis] wrote null-stub deployment → ${DEPLOYMENT_DST}\n`);
}

for (const t of TARGETS) syncAbi(t);
writeAbiBarrel();
syncDeployment();
